PixelFileName: "pixeldirection_v2withCommaRadians"
HH: 330

CircleCoords:
  XCoord: -145
  YCoord: 40

Radius:

  XMin: 4150
  XMax: 4300
  YMin: 100
  YMax: 200
  Jump: 3

  RadiusSqrt:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0
        Max: 0.7495
      InitTime:
        Value: 4150
        Min: 4100
        Max: 4200
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
    XMin: 4150
    XMax: 4300
    YMin: 100
    YMax: 200

  RadiusLinear:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0
        Max: 0.7495
      InitTime:
        Value: 4150
        Min: 4000
        Max: 4200
    XMin: 4200
    XMax: 4300
    YMin: 100
    YMax: 200

EnergyTime:

  Jump: 3
  XMin: 4200
  XMax: 4300
  YMin: 0
  YMax: 100

  Energy2:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0.7490
        Max: 0.7495
      InitTime:
        Value: 4150
        Min: 4100
        Max: 4200
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: 4000
    XMax: 4400
    YMin: 0
    YMax: 250

  Energy32:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0.7490
        Max: 0.7495
      InitTime:
        Value: 4150
        Min: 4100
        Max: 4200
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: 4000
    XMax: 4400
    YMin: 0
    YMax: 100

  EnergyLinear:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0.7490
        Max: 0.7495
      InitTime:
        Value: 4150
        Min: 4100
        Max: 4200
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: 4000
    XMax: 4400
    YMin: 0
    YMax: 250

  EnergyLog:
    XMin: 4000
    XMax: 4240
    YMin: 0
    YMax: 250

EnergyRadius:

  Jump: 1
  XMin: 100
  XMax: 160
  YMin: 0
  YMax: 100

  Energy2:
    Parameters:
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: 100
    XMax: 160
    YMin: 0
    YMax: 100

  Energy32:
    Parameters:
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: 100
    XMax: 160
    YMin: 0
    YMax: 100

  EnergyLinear:
    Parameters:
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: 100
    XMax: 160
    YMin: 0
    YMax: 100

  EnergyLog:
    XMin: 100
    XMax: 160
    YMin: 0
    YMax: 100

EnergyAngle:
  Jump: 1
  XMin: 0
  XMax: 360
  YMin: 0
  YMax: 100
  Angle1Min: 5
  Angle1Max: 30
  Angle2Min: -30
  Angle2Max: -5
  FrameToPlot: 4223
  MaxHisto: 25