PixelFileName: "pixeldirection_v2withCommaRadians"
HH: 330

CircleCoords:
  XCoord: X circle center
  YCoord: Y circle center

Radius:

  XMin: minFrame
  XMax: maxFrame
  YMin: minDistance
  YMax: maxDistance
  Jump: 1

  RadiusSqrt:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0
        Max: 0.7495
      InitTime:
        Value: T0
        Min: minT0
        Max: maxT0
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
    XMin: minFrame
    XMax: maxFrame
    YMin: minDistance
    YMax: maxDistance

  RadiusLinear:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0
        Max: 0.7495
      InitTime:
        Value: T0
        Min: minT0
        Max: maxT0
    XMin: minFrame
    XMax: maxFrame
    YMin: minDistance
    YMax: maxDistance

EnergyTime:

  Jump: 1
  XMin: minFrame
  XMax: maxFrame
  YMin: 0
  YMax: maxEnergy

  Energy2:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0.7490
        Max: 0.7495
      InitTime:
        Value: T0
        Min: minT0
        Max: maxT0
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: minFrame
    XMax: maxFrame
    YMin: 0
    YMax: maxEnergy

  Energy32:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0.7490
        Max: 0.7495
      InitTime:
        Value: T0
        Min: minT0
        Max: maxT0
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: minFrame
    XMax: maxFrame
    YMin: 0
    YMax: maxEnergy

  EnergyLinear:
    Parameters:
      Velocity:
        Value: 0.7495
        Min: 0.7490
        Max: 0.7495
      InitTime:
        Value: T0
        Min: minT0
        Max: maxT0
      Altitude:
        Value: 10
        Min: 0.1
        Max: 50
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: minFrame
    XMax: maxFrame
    YMin: 0
    YMax: maxEnergy

  EnergyLog:
    XMin: minFrame
    XMax: maxFrame
    YMin: 0
    YMax: maxEnergy

EnergyRadius:

  Jump: 1
  XMin: minDistance
  XMax: maxDistance
  YMin: 0
  YMax: maxEnergy

  Energy2:
    Parameters:
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: minDistance
    XMax: maxDistance
    YMin: 0
    YMax: maxEnergy

  Energy32:
    Parameters:
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: minDistance
    XMax: maxDistance
    YMin: 0
    YMax: maxEnergy

  EnergyLinear:
    Parameters:
      E1:
        Value: 1
        Min: -999
        Max: 999
    XMin: minDistance
    XMax: maxDistance
    YMin: 0
    YMax: maxEnergy

  EnergyLog:
    XMin: minDistance
    XMax: maxDistance
    YMin: 0
    YMax: maxEnergy

EnergyAngle:
  Jump: 1
  XMin: 0
  XMax: 360
  YMin: 0
  YMax: maxEnergy
  Angle1Min: min angle 1
  Angle1Max: max angle 1
  Angle2Min: min angle 2
  Angle2Max: max angle 2
  FrameToPlot: frame to plot (for FrameAngles.png)
  MaxHisto: max histogram value (for FrameAngles.png)