RootFileName: "CPU_RUN_MAIN__2020_08_25__19_34_27__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 835
MaxHisto: 100
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330