RootFileName: "CPU_RUN_MAIN__2019_12_05__18_41_09__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 900
MaxHisto: 30
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 0
limXmax: 200
limYmin: 0
limYmax: 200
FrameEnd: 1070
Threshold: 15
NominalCentreX: 230
NominalCentreY: 190
GoodFrameStart: 975
GoodFrameEnd: 1020
NumBinsToPlot: 20
BinStart: 120
BinSize: 5