RootFileName: "CPU_RUN_MAIN__2020_12_10__00_49_41__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2610
MaxHisto: 20
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 50
limYmin: -200
limYmax: -50