RootFileName: "CPU_RUN_MAIN__2020_05_26__07_38_55__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 4150
MaxHisto: 25
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 100
limYmin: -200
limYmax: 200