RootFileName: "CPU_RUN_MAIN__2020_05_26__07_38_55__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 4150
MaxHisto: 25
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 20
limYmin: -90
limYmax: 200
FrameEnd: 4300
Threshold: 2
NominalCentreX: -140
NominalCentreY: 40
GoodFrameStart: 4222
GoodFrameEnd: 4274
NumBinsToPlot: 70
BinStart: 0
BinSize: 5