RootFileName: "CPU_RUN_MAIN__2020_08_26__08_00_08__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2205
MaxHisto: 15
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -200
limXmax: 50
limYmin: -200
limYmax: -90
FrameEnd: 2300
Threshold: 1
NominalCentreX: -35
NominalCentreY: -297
GoodFrameStart: 2270
GoodFrameEnd: 2298
NumBinsToPlot: 30
BinStart: 200
BinSize: 5