RootFileName: "CPU_RUN_MAIN__2021_01_20__23_06_41__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 735
MaxHisto: 40
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 200
limYmin: -200
limYmax: 50