RootFileName: "CPU_RUN_MAIN__2020_07_22__07_59_55__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2570
MaxHisto: 50
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -200
limXmax: 200
limYmin: -50
limYmax: 200
FrameEnd: 2680
Threshold: 5
NominalCentreX: 110
NominalCentreY: 260
GoodFrameStart: 2600
GoodFrameEnd: 2650
NumBinsToPlot: 35
BinStart: 200
BinSize: 5