RootFileName: "CPU_RUN_MAIN__2020_06_29__19_28_57__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2_oldFF"
FrameStart: 900
MaxHisto: 50
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 50
limYmin: -200
limYmax: 50
FrameEnd: 1020
Threshold: 5
NominalCentreX: -150
NominalCentreY: -400
GoodFrameStart: 950
GoodFrameEnd: 990
NumBinsToPlot: 50
BinStart: 320
BinSize: 5