RootFileName: "CPU_RUN_MAIN__2020_08_25__19_36_42__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 30
MaxHisto: 100
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 90
limXmax: 200
limYmin: -90
limYmax: -50
FrameEnd: 120
Threshold: 50
NominalCentreX: 200
NominalCentreY: -25
GoodFrameStart: 80
GoodFrameEnd: 120
NumBinsToPlot: 25
BinStart: 50
BinSize: 5