RootFileName: "CPU_RUN_MAIN__2019_12_05__18_37_35__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 130
MaxHisto: 100
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 200
limYmin: -200
limYmax: 50
FrameEnd: 390
Threshold: 15
NominalCentreX: 285
NominalCentreY: -210
GoodFrameStart: 220
GoodFrameEnd: 347
NumBinsToPlot: 81
BinStart: 180
BinSize: 5