RootFileName: "CPU_RUN_MAIN__2021_01_09__06_07_24__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 1510
MaxHisto: 40
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 50
limYmin: -50
limYmax: 100