RootFileName: "CPU_RUN_MAIN__2020_07_21__19_41_55__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 1700
MaxHisto: 10
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -200
limXmax: -70
limYmin: 40
limYmax: 200
FrameEnd: 1825
Threshold: 2
NominalCentreX: -210
NominalCentreY: 180
GoodFrameStart: 1790
GoodFrameEnd: 1810
NumBinsToPlot: 80
BinStart: 100
BinSize: 5