RootFileName: "CPU_RUN_MAIN__2020_07_22__07_59_55__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 280
MaxHisto: 10
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330