RootFileName: "CPU_RUN_MAIN__2021_01_09__07_43_31__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 10040
MaxHisto: 15
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -200
limXmax: 200
limYmin: -200
limYmax: 0
FrameEnd: 10115
Threshold: 1
NominalCentreX: 100
NominalCentreY: -350
GoodFrameStart: 10050
GoodFrameEnd: 10060
NumBinsToPlot: 38
BinStart: 200
BinSize: 5