RootFileName: "CPU_RUN_MAIN__2020_03_03__02_29_21__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2865
MaxHisto: 20
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 50
limXmax: 200
limYmin: -50
limYmax: 50
FrameEnd: 3020
Threshold: 8
NominalCentreX: 170
NominalCentreY: 70
GoodFrameStart: 2931
GoodFrameEnd: 2954
NumBinsToPlot: 25
BinStart: 40
BinSize: 5