RootFileName: "CPU_RUN_MAIN__2019_12_30__18_15_11__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 7300
MaxHisto: 30
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 50
limXmax: 200
limYmin: 50
limYmax: 200
FrameEnd: 7420
Threshold: 10
NominalCentreX: 135
NominalCentreY: 200
GoodFrameStart: 7360
GoodFrameEnd: 7410
NumBinsToPlot: 15
BinStart: 100
BinSize: 5