RootFileName: "CPU_RUN_MAIN__2020_03_03__02_29_21__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2865
MaxHisto: 20
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 50
limXmax: 200
limYmin: -50
limYmax: 50