RootFileName: "CPU_RUN_MAIN__2020_12_10__00_49_41__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2610
MaxHisto: 20
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 0
limXmax: 50
limYmin: -200
limYmax: -50
FrameEnd: 2760
Threshold: 2
NominalCentreX: 150
NominalCentreY: -70
GoodFrameStart: 2677
GoodFrameEnd: 2701
NumBinsToPlot: 25
BinStart: 90
BinSize: 5