RootFileName: "CPU_RUN_MAIN__2020_09_15__00_25_23__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 8360
MaxHisto: 10
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: 20
limXmax: 200
limYmin: 90
limYmax: 200
FrameEnd: 8470
Threshold: 1
NominalCentreX: 120
NominalCentreY: 220
GoodFrameStart: 8430
GoodFrameEnd: 8460
NumBinsToPlot: 30
BinStart: 120
BinSize: 5