RootFileName: "CPU_RUN_MAIN__2020_03_03__02_29_21__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 3755
MaxHisto: 20
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -200
limXmax: -90
limYmin: 0
limYmax: 50
FrameEnd: 3840
Threshold: 5
NominalCentreX: -280
NominalCentreY: 190
GoodFrameStart: 3815
GoodFrameEnd: 3835
NumBinsToPlot: 12
BinStart: 220
BinSize: 5