RootFileName: "CPU_RUN_MAIN__2020_08_26__08_00_08__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2"
FrameStart: 2205
MaxHisto: 15
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330