RootFileName: "CPU_RUN_MAIN__2020_06_29__19_28_57__950Cathode3FullPDMonlyself_"
Version: "l1_v11r2_oldFF"
FrameStart: 900
MaxHisto: 50
PixelFileName: "pixeldirection_v2withCommaRadians"
ApplyTimeCorr: 1
HH: 330
limXmin: -50
limXmax: 50
limYmin: -150
limYmax: 50
FrameEnd: 1020
Threshold: 5
NominalCentreX: -90
NominalCentreY: -300
GoodFrameStart: 990
GoodFrameEnd: 1015
NumBinsToPlot: 50
BinStart: 500
BinSize: 5